<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-07-01 18:46
=======
# Generated by Django 6.0.6 on 2026-07-01 00:05
>>>>>>> 42cb02ce311e40ac2bfb61be4ea2752dbb10aa74

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
